st_dota/matches/urls.py
from django.urls import path
from . import views


app_name = 'matches'

urlpatterns = [
	path('', views.DotaMatches.as_view(), name='dota_matches')
]

st_dota/st_dota/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomepageTemplateView.as_view(), name='homepage'),
    path('teams/', include('teams.urls')),
    path('matches/', include('matches.urls')),
]


# Point to Django where the Media Files are located in DEBUG mode

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

st_dota/teams/urls.py
from django.urls import path
from . import views


# namespace
app_name = 'teams'

urlpatterns = [
    path('', views.RegionList.as_view(), name='region_list'),
    path('<int:pk>/', views.RegionDetail.as_view(), name='region_detail'),
]

st_dota/matches/models.py
from django.db import models

# Create your models here.

st_dota/teams/models.py
from django.db import models

# Create your models here.


class Region_Name(models.Model):
    reg_name = models.CharField(max_length=150, unique=True)
    region_image = models.ImageField(upload_to='reg_images', blank=True)

    def __str__(self):
        return self.reg_name


class Team_Name(models.Model):
    name_team = models.CharField(max_length=250, unique=True)
    logo = models.ImageField(upload_to='team_logos', blank=True)
    region_member = models.ForeignKey(Region_Name, related_name='regions', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name_team + ' - ' + str(self.region_member)


class Team_Member(models.Model):

    # Position values in drop down list
    POSITIONS = (
                (1, 1),
                (2, 2),
                (3, 3),
                (4, 4),
                (5, 5),
    )

    member_name = models.CharField(max_length=250)
    position = models.PositiveIntegerField(choices=POSITIONS)
    member_team = models.ForeignKey(Team_Name, related_name='teams', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.member_name + ' - ' + str(self.member_team) + ' - ' + str(self.position)

st_dota/matches/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from datetime import datetime, timedelta
import requests
import timeago


class DotaMatches(TemplateView):
    template_name = 'matches/dota_matches.html'

    def get(self, request, *args, **kwargs):
        # Get the URL of the API using requests module
        url = requests.get('https://api.opendota.com/api/proMatches')
        # Decode the data
        json_data = url.json()

        # List that will contain dictionaries
        game_data = []

        for data in json_data:
            # Will contain the values from the dictionary data of json_data
            j_data = {}
            j_data['League'] = data['league_name']
            j_data['Radiant'] = data['radiant_name']
            j_data['Dire'] = data['dire_name']
            j_data['Duration'] = str(timedelta(seconds=data['duration']))
            j_data['Finished'] = timeago.format(datetime.now() - datetime.fromtimestamp(data['start_time']))

            # Check who the winner of the match
            if data['radiant_win'] == False:
                j_data['Winner'] = data['dire_name']
            else:
                j_data['Winner'] = data['radiant_name']

            # Put the data in our game_data list
            game_data.append(j_data)

        return render(request, self.template_name, {'game_data': game_data})

st_dota/st_dota/views.py
from django.views.generic import TemplateView


class HomepageTemplateView(TemplateView):
	template_name = 'st_dota/homepage.html'

st_dota/teams/views.py
from django.views.generic import ListView, DetailView
from .models import Region_Name
# Create your views here.


class RegionList(ListView):
    model = Region_Name
    context_object_name = 'region_list'
    template_name = 'teams/region_list.html'


class RegionDetail(DetailView):
    model = Region_Name
    context_object_name = 'region_detail'
    template_name = 'teams/region_detail.html'

st_dota/templates/matches/dota_matches.html
{% extends 'st_dota/base.html' %}


{% block title_block %}DOTA 2 Pro Matches{% endblock %}


{% block body_block %}
	<div class="row">
		<div class="col-lg-12 col-matches">
			
			<div class="table-matches table-responsive">
				<table class="table table-condensed">
					<thead class="matches-head">
						<th>League</th>
						<th>Radiant</th>
						<th>Dire</th>
						<th>Duration</th>
						<th>Finished</th>
						<th>Winner</th>
					</thead>

					<tbody class="matches-data">
						<!-- Loop through json data -->
						{% for data in game_data %}
							<tr class="data-result">
								{% for value in data.items %}
									<td>{{value.1}}</td>
								{% endfor %}
							</tr>
						{% endfor %}
					</tbody>

				</table>
			</div>

		</div>
	</div>
 
{% endblock %}

st_dota/templates/st_dota/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title_block %}BASE{% endblock %}</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<!-- Load staticfiles -->
	{% load staticfiles %}
	<link href="https://fonts.googleapis.com/css?family=Frijole" rel="stylesheet"> 
	<link rel="stylesheet" type="text/css" href="{% static 'st_dota/st_style.css' %}">
	

	

</head>
<body>

	<!-- Navbar -->
	<nav class="navbar-custom navbar navbar-default navbar-static-top" >
		<div class="container">
			<div class="navbar-header">
				<!-- Hamburger Icon -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navCol">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

				<!-- Brand -->
				<a href="{% url 'homepage' %}" class="navbar-brand">-root- DOTA</a>
			</div>

			<div class="collapse navbar-collapse" id="navCol">
				<ul class="nav navbar-nav">
					<li class="divider">
						<a href="{% url 'teams:region_list' %}" class="navbar-link">TEAMS</a>
					</li>

					<li class="divider">
						<a href="{% url 'matches:dota_matches' %}" class="navbar-link">MATCHES</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>


	<!--  Main Content -->
	<div class="container">
		{% block body_block %}

		{% endblock %}
	</div>





	<!-- Footer -->
	<footer class="footer">
      <div class="container">
        <p class="text-muted">-root- DOTA</p>
      </div>
    </footer>


	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

st_dota/templates/st_dota/homepage.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>-Root- DOTA - eSports | Media</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<!-- Load staticfiles -->
	{% load staticfiles %}
	<link href="https://fonts.googleapis.com/css?family=Frijole" rel="stylesheet"> 
	<link rel="stylesheet" type="text/css" href="{% static 'st_dota/st_style.css' %}">
	

	

</head>
<body>

	<!-- Navbar -->

	<nav class="navbar-custom navbar navbar-default navbar-static-top" >
		<div class="container">
			<div class="navbar-header">
				<!-- Hamburger Icon -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navCol">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

				<!-- Brand -->
				<a href="{% url 'homepage' %}" class="navbar-brand">-root- DOTA</a>
			</div>

			<div class="collapse navbar-collapse" id="navCol">
				<ul class="nav navbar-nav">
					<li class="divider">
						<a href="{% url 'teams:region_list' %}" class="navbar-link">TEAMS</a>
					</li>

					<li class="divider">
						<a href="{% url 'matches:dota_matches' %}" class="navbar-link">MATCHES</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	

	<!--  Main Content -->
	<div class="container custom-container">
			
		<div class="row">
			<div class="col-lg-8">
				<div class="news-dota">
					news
				</div>
			</div>

			<div class="col-lg-4" >
				<div class="patches-dota">
					latest patches
				</div>
			</div>

			<div class="col-lg-4" >
				<div class="promatches-dota">
					promatches
				</div>
			</div>

			<div class="col-lg-4 " >
				<div class="extra-space">
					DOTA 2 Teams
				</div>
			</div>
			
			<div class="col-lg-4" >
				<div class="upcoming-events">
					events
				</div>	
			</div>
		</div>
	</div>





	<!-- Footer -->
	<footer class="footer">
      <div class="container">
        <p class="text-muted">-root- DOTA</p>
      </div>
    </footer>


	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

st_dota/templates/teams/region_detail.html
{% extends 'st_dota/base.html' %}


{% block title_block %} {{region_detail.reg_name}} DOTA 2 Teams {% endblock %}


{% block body_block %}
	
	<div class="row">
		{% for region in region_detail.regions.all %}
			<div class="col-lg-4 col-md-4 col-sm-6 teams-div">
				<div class="team-logo-div">
					<img src="{{ region.logo.url }}" alt="Image not found." class="center-block team-logo">
				</div>

				<h3 class="team-name">{{ region.name_team }}</h3>

				<div class="table-responsive">
						<table class="table team-table">
							<thead>
								<th>Position</th>
								<th>ID</th>
							</thead>

							<tbody>
								<!-- Loop through the members -->
								{% for member in region.teams.all %}
								<tr>
									<td>{{ member.position }}</td>
									<td>{{ member.member_name }}</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
			</div>
		{% endfor %}
	</div>

{% endblock %}

st_dota/templates/teams/region_list.html
{% extends 'st_dota/base.html' %}


{% block title_block %}DOTA 2 Regions - Browse Teams Per Region{% endblock %}


{% block body_block %} 

	
	<div class="row">
		{% for region in region_list %}
		<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 custom-col">
			
				<a href="{{ region.id }}">
					<div class="region-name">
						<img src="{{ region.region_image.url }}" alt="Image not found" class="reg-image center-block">
					</div>
				</a>
					<h2>{{ region.reg_name }}</h2>	
		</div>
		{% endfor %}
	</div>


{% endblock %}